### PR TITLE
Add option to disable port scans 

### LINKED ISSUE #75: Add an option to disable port scans
These can take quite a while (due to timeouts) and aren't always relevant, so a user should be allowed to disable them with a command-line option.

Something similar to what we do with `testssl` would probably be best.

### PR DESCRIPTION
**Pull request by altmas5**
Closes #75

### CODE REVIEW

**Comment by altmas5** [comment]
I'm not sure if the @CLAassistant page is configurable, but I've found hard to read the hex color #2c3e50 over white color with that thin typography, maybe I need to go to the ophthalmologist again.

**Comment by woodruffw** [comment]
This looks great, thank you! Would you mind updating the manpage (`twa.1`) as well?

**Comment by woodruffw** [comment]
> I'm not sure if the @CLAassistant page is configurable, but I've found hard to read the hex color #2c3e50 over white color with that thin typography, maybe I need to go to the ophthalmologist again.

Yeah, I've had the same problem. I don't believe it is configurable, unfortunately :disappointed:

**Comment by altmas5** [comment]
> This looks great, thank you! Would you mind updating the manpage (`twa.1`) as well?

Sure, I added an additional commit with the man page updated. :+1:

**Comment by woodruffw** [comment]
Fantastic, thanks. I made one small additional manpage change, will merge when CI goes through.

**Comment by altmas5** [comment]
> Fantastic, thanks. I made one small additional manpage change, will merge when CI goes through.

Oh, yes I forgot a to update that at the man page. Cool :+1:
Let's see on which other issue I can help

**Comment by woodruffw** [comment]
> Let's see on which other issue I can help

I appreciate it!

**Pull request merged**
